
package com.autoserviciosap.resources.ZWS_DESBLOQUEO_USUARIOS;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Holder;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.3.1 Generated source
 * version: 2.2
 * 
 */
@WebService(name = "ZWSBloqueo_Desbloqueo_Usrs", targetNamespace = "urn:sap-com:document:sap:rfc:functions")
@XmlSeeAlso({ ObjectFactory.class })
public interface ZWSBloqueoDesbloqueoUsrs {

	/**
	 * 
	 * @param password
	 * @param tipo
	 * @param opcion
	 * @param newPASSWORD
	 * @param password2
	 * @param message
	 * @param email
	 * @param username
	 */
	@WebMethod(
			operationName = "ZMF_DESBLO_USUARIO",
			action = "urn:sap-com:document:sap:rfc:functions:ZWSBloqueo_Desbloqueo_Usrs:ZMF_DESBLO_USUARIORequest")
	@RequestWrapper(
			localName = "ZMF_DESBLO_USUARIO",
			targetNamespace = "urn:sap-com:document:sap:rfc:functions",
			className = "com.autoserviciosap.resources.ZWS_DESBLOQUEO_USUARIOS.ZMFDESBLOUSUARIO")
	@ResponseWrapper(
			localName = "ZMF_DESBLO_USUARIOResponse",
			targetNamespace = "urn:sap-com:document:sap:rfc:functions",
			className = "com.autoserviciosap.resources.ZWS_DESBLOQUEO_USUARIOS.ZMFDESBLOUSUARIOResponse")
	public void zmfDESBLOUSUARIO( //
			@WebParam(name = "DESTINO", targetNamespace = "") String destino,
			@WebParam(name = "EMAIL", targetNamespace = "") String email,
			@WebParam(name = "NEW_PASSWORD", targetNamespace = "") String newPASSWORD,
			@WebParam(name = "OPCION", targetNamespace = "") String opcion,
			@WebParam(name = "PASSWORD", targetNamespace = "") String password,
			@WebParam(name = "USERNAME", targetNamespace = "") String username,
			@WebParam(name = "MESSAGE", targetNamespace = "", mode = WebParam.Mode.OUT) Holder<String> message,
			@WebParam(name = "PASSWORD2", targetNamespace = "", mode = WebParam.Mode.OUT) Holder<String> password2,
			@WebParam(name = "TIPO", targetNamespace = "", mode = WebParam.Mode.OUT) Holder<String> tipo,
			@WebParam(name = "TITULO", targetNamespace = "", mode = WebParam.Mode.OUT) Holder<String> titulo);
	//

}
